spring.application.name=expense-tracker-spring
# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=musa2002
spring.datasource.driver-class-name=org.postgresql.Driver

# Disable Flyway (since we're using an existing database owned by the Python project)
spring.flyway.enabled=false

# Validate entities against existing tables, but don't modify anything
spring.jpa.hibernate.ddl-auto=none

# Show SQL queries in logs (useful for learning and debugging)
spring.jpa.show-sql=true
server.port=8081